#!/usr/bin/env python3
"""Bake VideoObject structured data into video.html from videos.json.

video.html builds its YouTube iframes in JavaScript at runtime, so the raw HTML
Google crawls contains no video at all. This writes a static schema.org
VideoObject for each video into the page, which is what Google actually reads
when deciding whether to index a video.

Every required VideoObject field is filled from real data: name, description,
thumbnailUrl, uploadDate, duration, embedUrl and contentUrl. uploadDate and
duration live in videos.json and come from the YouTube watch pages -- do not
guess them, an invented uploadDate is worse than no markup.

Rewrites one marked region in video.html:
  * VIDEOS-JSONLD  -- <script type="application/ld+json"> with an ItemList of
                      VideoObject entries

Usage:  python tools/build_videos.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "video.html"
DATA = ROOT / "videos.json"
SITE = "https://www.mikidrummer.ca"
PAGE_URL = f"{SITE}/video.html"

START = "<!-- VIDEOS-JSONLD:START (generated by tools/build_videos.py — edit videos.json instead) -->"
END = "<!-- VIDEOS-JSONLD:END -->"


def video_object(v: dict, position: int) -> dict:
    """One schema.org VideoObject. Missing uploadDate/duration are omitted, not faked."""
    vid = v["id"]
    title = v["title"]
    obj = {
        "@type": "VideoObject",
        "position": position,
        "name": title,
        "description": (
            f"{title} — drums by Miki Drummer, a Vancouver, BC session and live "
            f"drummer. From the Miki Drummer YouTube channel."
        ),
        "thumbnailUrl": [f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg"],
        "embedUrl": f"https://www.youtube.com/embed/{vid}",
        "contentUrl": f"https://www.youtube.com/watch?v={vid}",
        "url": f"{PAGE_URL}#{vid}",
        "publisher": {
            "@type": "Person",
            "name": "Miki Drummer",
            "url": SITE,
        },
    }
    if v.get("uploadDate"):
        obj["uploadDate"] = v["uploadDate"]
    if v.get("duration"):
        obj["duration"] = v["duration"]
    return obj


def build(data: dict) -> str:
    videos = [data["featured"], *data.get("sidebar", [])]
    payload = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "Miki Drummer — drum videos",
        "itemListElement": [video_object(v, i) for i, v in enumerate(videos, 1)],
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return f'{START}\n<script type="application/ld+json">\n{body}\n</script>\n{END}'


def main() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    html = PAGE.read_text(encoding="utf-8")

    if START not in html or END not in html:
        raise SystemExit(
            f"Markers not found in {PAGE.name}. Add these two lines inside <head>:\n"
            f"  {START}\n  {END}"
        )

    block = build(data)
    new = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _: block,
        html,
        flags=re.S,
    )

    n = len(data.get("sidebar", [])) + 1
    if new == html:
        print(f"video.html: already up to date ({n} videos)")
        return
    PAGE.write_text(new, encoding="utf-8")
    print(f"video.html: baked VideoObject data for {n} videos")


if __name__ == "__main__":
    main()
